Spellcheck on CI (#6890)
See https://github.com/codespell-project/codespell

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -48,3 +48,17 @@ jobs:
         uses: codecov/codecov-action@v3
         with:
           files: ./.coverage/lcov.info
+
+  spellcheck:
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Install codespell
+        run: pip install codespell
+
+      - name: Spellcheck
+        # Ignore a CI failure because there are false positives.
+        run: codespell || echo 'Fix misspells via "codespell" on your console, or ignore false positives.'
